FROM python:3.8-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /usr/src/

# Copier le dossier app et requirements.txt dans le conteneur
COPY ./app1 ./app
COPY Pipfile Pipfile.lock ./

# Installer les dépendances Python
RUN python -m pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install --system --deploy --ignore-pipfile

# Définir PYTHONPATH pour inclure le répertoire où se trouve le package 'app'
ENV PYTHONPATH="${PYTHONPATH}:/usr/src/app"

# Exposer le port sur lequel l'application va s'exécuter
EXPOSE 8000

# Définir la commande pour exécuter l'application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]